### ISSUE TITLE
검색 엑박 이미지 예외처리

### ISSUE THREAD

**Issue by ystone-dev** [FRONTENDSCHOOL5/final-15-Tripillow#193]
## :bookmark_tabs: 이슈 내용
검색 시 이미지가 제대로 나오지 않을 시 검색결과에서 제외

## :pencil:  작업 내용
- [x] 검색 엑박 이미지 예외처리

## :round_pushpin:ETC
기타사항

**Comment by bringvotrevin** [comment]
닫아드릴게요
