### ISSUE TITLE
각 페이지 padding-bottom 수정, 랜딩페이지 수정, 모바일 뷰포트 100vh 수정

### ISSUE THREAD

**Issue by haron-lee** [FRONTENDSCHOOL5/final-15-Tripillow#195]
## :bookmark_tabs: 이슈 내용
랜딩 페이지, 프로필 페이지

## :pencil:  작업 내용
- [x] 랜딩페이지 login method height 수정 
- [x] 모바일 뷰포트 100vh 대응
- [x] 각 페이지 마지막 게시물 padding-bottom (height 변경으로 인한 UI padding-bottom 수정)  
- [x] Navbar 컴포넌트 자체에 footer태 그 추가, 각자 넣었던 footer 태그 삭제
- [x] 최상위 Layout 스타일 border top과 bottom 제거
- [x] 프로필 피드 버튼 수정 (Recoil로 상태저장)
- [x] 로그아웃시 whichView atom 초기화 
- [x] 상품디테일 페이지 footer backgroundColor 추가

## :round_pushpin:ETC
기타사항

**Comment by bringvotrevin** [comment]
닫아드릴게요!
